import Layout from "@/components/layout/Layout";
import classes from "./b.module.css"
export const metadata = {
  title: "NotFoud",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={classes.body}>
        {children} 
      </body>
    </html>
  );
}
